name: Publish
on: [ workflow_dispatch ]
jobs:
  matrix_prep:
    uses: ./.github/workflows/matrix_prep.yml

  display_versions:
    needs: matrix_prep
    runs-on: ubuntu-22.04
    steps:
      - name: display versions
        run: echo '${{ needs.matrix_prep.outputs.versions }}' | jq '.include[].version_range[]'

  publish:
    needs: matrix_prep
    runs-on: ubuntu-22.04

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix_prep.outputs.versions) }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: wrapper validation
        uses: gradle/actions/wrapper-validation@v3

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: run publish script
        run: python3 publish.py
        env:
          MC_VERSIONS: ${{ join(matrix.version_range, ',') }}
          MAVEN_URL: ${{ secrets.NEW_MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.NEW_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEW_MAVEN_PASSWORD }}
